### ISSUE TITLE
Larger hero images

### ISSUE THREAD

**Issue by scottwebster** [scottwebster/scottwebster.github.io#15]
What do you think about larger hero images at the top of all but the main title page?  Like the MTA site - http://www.mountain-training.org/associations

**Comment by kenners** [comment]
Mixed opinion - I think it works for the MTA site as they're using it as a backdrop for loading a sidemenu onto it as part of their toplevel nav. However, it also shoves their content below the fold on the page.

Given that we've already established the toplevel nav using a top navbar, I don't think there's a compelling reason to make the pictures bigger, unless you feel strongly the other way.

**Comment by kenners** [comment]
@scottwebster Are we ok to close this for the time being, as I probably don't have the time at present to undertake a significant redesign. Happy to revisit/reopen this in the future if desired.

**Comment by scottwebster** [comment]
Yeh dude no worries at all!

Scott Webster
07775664642
www.scottwebster.co.uk
