### ISSUE TITLE
Import blog posts from old site to new one

### ISSUE THREAD

**Issue by scottwebster** [scottwebster/scottwebster.github.io#16]
Not sure how to go about this? Would be nice to do at some point. :)

**Comment by kenners** [comment]
Can you follow the export steps detailed here:
https://support.google.com/blogger/answer/97416

and then attach the resulting XML file to this issue thread.

I'll then try and conjure some magic.

Where would you want the posts to be imported to? Presumably /exped/antarctica?

**Comment by scottwebster** [comment]
The blog post would predominantly need to be added to Antarctica but there are some that would need to go into blog (i.e. UK posts) and one or 2 for Alaska.  I can't seem to add the XML file here...will e-mail it to you.

**Comment by kenners** [comment]
Fixed by merging #21.
