### ISSUE TITLE
Gallery page?

### ISSUE THREAD

**Issue by scottwebster** [scottwebster/scottwebster.github.io#19]
Look into setting up a gallery page with some of by best photos from various trips?

**Comment by kenners** [comment]
This would require a custom plugin for Jekyll, and would not work with Github hosting, as Github doesn't permit third-party Jekyll plugins.

It would be possible if hosting were moved elsewhere (i.e. using paid hosting).

One alternative might be to create a Set on Mairi's Flickr account containing photos, and then we could create a top-level link from the nav bar to that set on Flickr.

**Comment by kenners** [comment]
Closing for time being - happy to discuss further.
