### ISSUE TITLE
Move title from herobar to topbar

### ISSUE THREAD

**Issue by scottwebster** [scottwebster/scottwebster.github.io#2]
Dear sir, if possible could you please move the title "Scott Webster Mountaineering" to the navigation bar next to the logo and remove it from the 'hero' bar photo.  In an ideal world it would be in a little rectangle to make it stand out similar to the one on this site - http://www.edfarrelly.com/

Thank you please!

**Comment by kenners** [comment]
Realised this should have been closed a while back.
