### ISSUE TITLE
RSS feed or way to subscribe to updates on expedition blogs?

### ISSUE THREAD

**Issue by scottwebster** [scottwebster/scottwebster.github.io#20]
Someone was asking about this...is it possible? or an alternative way to achieve this sort of thing?

**Comment by kenners** [comment]
There was already a global RSS feed for all posts on the site, available at (and advertised within the code):
http://www.scottwebster.co.uk/feed.xml

I've also added individual expedition feeds:
http://www.scottwebster.co.uk/exped/antarctica/feed.xml
http://www.scottwebster.co.uk/exped/overland-mountaineering/feed.xml
